parameters:
    the_rat_branching.helper.database.class: TheRat\BranchingBundle\Helper\Database

services:
    the_rat_branching.helper.database:
        class: %the_rat_branching.helper.database.class%
        arguments:
            - %kernel.root_dir%
            - %the_rat_branching.copy_db_data%
            - %database_driver%
            - %database_host%
            - %database_port%
            - %database_user%
            - %database_password%
            - %database_name%
            - %database_name_original%
