parameters:
    therat.branching.helper.database.class: TheRat\BranchingBundle\Helper\Database

services:
    therat_symdep.helper.database:
        class: %therat.branching.helper.database.class%
        calls:
            - [ setContainer, [ @service_container ] ]